// SPDX-License-Identifier: MIT-0

export interface ConfiguracaoPontuacao {
  PENALIDADE_MISSING_REQUIRED: number;
  PESO_OPTIONAL: number;
  PESO_REQUIRED: number;
  PESO_DEPENDENCIA: number;
  PESO_PADRAO: number;
  PENALIDADE_FORBIDDEN: number;
  FATOR_ESCALA_TAMANHO_MAX: number;
  FATOR_COMPLEXIDADE_MAX: number;
  FATOR_MATURIDADE_MAX: number;
  THRESHOLD_CONFIANCA_MINIMA: number;
  THRESHOLD_DIFERENCA_DOMINANTE: number;
  THRESHOLD_HIBRIDO_REAL: number;
  BONUS_COMPLETUDE_BASE: number;
  BONUS_ESPECIFICIDADE_MULTIPLIER: number;
  PENALIDADE_GENERICO_EXTREMA: number;
  AJUSTE_CONFIANCA_PROJETO_GRANDE: number;
  AJUSTE_CONFIANCA_PROJETO_PEQUENO: number;
  LIMITE_ARQUIVOS_GRANDE: number;
  LIMITE_ARQUIVOS_PEQUENO: number;
  LIMITE_FUNCOES_MATURIDADE: number;
  MULTIPLICADOR_MATURIDADE: number;
}
